# Generated by Django 5.1.3 on 2024-12-01 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_and_assessment_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accommodation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('out_of_office_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('travel_and_assessment_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_added_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('case', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_feenote_case', to='Cases.case')),
            ],
        ),
    ]
