# Generated by Django 5.1.3 on 2024-12-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeNotes', '0002_feenote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feenote',
            name='valid_fee_note',
            field=models.FileField(null=True, upload_to='FeeNotes/files'),
        ),
    ]
