# Generated by Django 5.1.3 on 2024-12-01 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Assessors', '0001_initial'),
        ('Cases', '0001_initial'),
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='cases',
            field=models.ManyToManyField(blank=True, related_name='assessor_cases', to='Cases.case'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='staff',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Staff.staff'),
        ),
    ]
