# Generated by Django 5.1.3 on 2024-12-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessors', '0002_initial'),
        ('FeeNotes', '0001_initial'),
        ('Reports', '0004_report_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessor',
            name='fee_notes',
            field=models.ManyToManyField(blank=True, related_name='assessor_fee_notes', to='FeeNotes.feenote'),
        ),
        migrations.AddField(
            model_name='assessor',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='assessor_reports', to='Reports.report'),
        ),
    ]
