# Generated by Django 5.1.3 on 2024-12-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
        ('Staff', '0002_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='appointments',
            field=models.ManyToManyField(blank=True, related_name='assessor_appointments', to='Appointments.appointment'),
        ),
    ]
