# Generated by Django 5.1.3 on 2025-01-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
        ('Staff', '0006_staff_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='staff_notifications', to='Notifications.notification'),
        ),
    ]
