# Generated by Django 5.1.3 on 2024-12-01 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cases', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date_reported',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='case',
            name='insurance_Company',
            field=models.CharField(choices=[('MUA', 'MUA Insurance (U) LTD'), ('MF', 'Mayfair Insurance Uganda LTD'), ('UAP', 'Old Mutual Insurance Uganda LTD'), ('JIC', 'Jubilee Alliance General Insurance Company'), ('BIC', 'Britam Insurance Company'), ('EXCEL', 'Excel Insurance Company LTD'), ('APA', 'APA Insurance (U) LTD'), ('AL', 'Alliance Africa General Insurance LTD'), ('LG', 'Liberty General Insurance (U) LTD'), ('GA', 'GA Insurance Uganda'), ('ICEA', 'ICEA Lion General Insurance LTD')], default='Not Selected', max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='policy',
            field=models.CharField(choices=[('IAR', 'Industrial All Risks Insurance Policy'), ('GIT', 'Marine Goods in Transit Insurance Policy'), ('FR', 'Fire & Allied Peril Insurance Policy'), ('FMD', 'Fire Material Damage Policy'), ('CAR', "Contractor's All Risk Insurance"), ('MT', 'Commercial Motor Policy')], default='Not Selected', max_length=50),
        ),
    ]
