# Generated by Django 5.1.3 on 2024-12-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cases', '0003_alter_case_date_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
