# Generated by Django 5.1.3 on 2024-12-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cases', '0004_case_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='policy',
            field=models.CharField(choices=[('IAR', 'Industrial All Risks Insurance Policy'), ('GIT', 'Marine Goods in Transit Insurance Policy'), ('FR', 'Fire & Allied Peril Insurance Policy'), ('FMD', 'Fire Material Damage Policy'), ('CAR', "Contractor's All Risk Insurance"), ('MT', 'Commercial Motor Policy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='Pending', max_length=50),
        ),
    ]
