# Generated by Django 5.1.3 on 2024-12-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cases', '0005_alter_case_policy_alter_case_status'),
        ('SupportDocuments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='support_documents',
            field=models.ManyToManyField(blank=True, related_name='case_support_documents', to='SupportDocuments.supportdocument'),
        ),
    ]
