# Generated by Django 5.1.3 on 2024-12-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cases', '0006_case_support_documents'),
        ('Pictures', '0002_picture_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='case_pictures', to='Pictures.picture'),
        ),
    ]
