# Generated by Django 5.1.3 on 2024-12-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cases', '0007_alter_case_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='company_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
