# Generated by Django 5.1.3 on 2025-01-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cases', '0008_case_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='field_notes',
            field=models.FileField(null=True, upload_to='CaseFieldNotes/files'),
        ),
    ]
