# Generated by Django 5.1.3 on 2024-12-22 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=100, null=True)),
                ('last_sent', models.DateTimeField(null=True)),
                ('run_until', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Paused', 'Paused'), ('Stopped', 'Stopped')], max_length=100)),
            ],
        ),
    ]
