# Generated by Django 5.1.3 on 2024-12-03 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_alter_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_uploaded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
