# Generated by Django 5.1.3 on 2024-12-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0004_report_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Submitted', 'Submitted')], default='In Progress', max_length=50),
        ),
    ]
