# Generated by Django 5.1.3 on 2025-01-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0005_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Approved', 'Approved')], default='In Progress', max_length=50),
        ),
    ]
