# Generated by Django 5.1.3 on 2024-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationlink',
            name='department',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Assessors', 'Assessors'), ('Administration', 'Administration')], max_length=100, null=True),
        ),
    ]
